export {
  createWorkspaceRegistry,
  isAnnotatedWorkspace,
  liveWorkspaces,
  observationMatchesRow,
  WorkspaceRegistry,
  workspaceObservationFromRecord,
  workspaceRegistryTable,
  type WorkspaceClaimError,
  type WorkspaceClaimInput,
  type WorkspaceHostIdentity,
  type WorkspaceObservation,
  type WorkspaceRegistryOptions,
  type WorkspaceRetrackError,
} from './workspace-registry';
